<a href="https://colab.research.google.com/github/Odima-dev/Data-Science-and-Machine-Learning/blob/main/Implementationofmatrixproduct.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [8]:
#Problem 1: Matrix product is calculated manually
"""
Row 0 × Columns of B:

- C[0][0] = (-1)(0) + (2)(0) + (3)(2) = 0 + 0 + 6 = 6
- C[0][1] = (-1)(2) + (2)(2) + (3)(9) = -2 + 4 + 27 = 29
- C[0][2] = (-1)(1) + (2)(-8) + (3)(-1) = -1 - 16 - 3 = -20

Row 1 × Columns of B:

- C[1][0] = (4)(0) + (-5)(0) + (6)(2) = 0 + 0 + 12 = 12
- C[1][1] = (4)(2) + (-5)(2) + (6)(9) = 8 - 10 + 54 = 52
- C[1][2] = (4)(1) + (-5)(-8) + (6)(-1) = 4 + 40 - 6 = 38

Row 2 × Columns of B:

- C[2][0] = (7)(0) + (8)(0) + (-9)(2) = 0 + 0 - 18 = **-18**
- C[2][1] = (7)(2) + (8)(2) + (-9)(9) = 14 + 16 - 81 = **-51**
- C[2][2] = (7)(1) + (8)(-8) + (-9)(-1) = 7 - 64 + 9 = **-48**

Resulting Matrix C:

[[   6   29  -20]
 [  12   52   38]
 [ -18  -51  -48]]

"""

#Problem 2: Calculation by NumPy function
import numpy as np

# Defining matrices A and B
a_ndarray = np.array([[-1, 2, 3], [4, -5, 6], [7, 8, -9]])
b_ndarray = np.array([[0, 2, 1], [0, 2, -8], [2, 9, -1]])

# Using np.matmul
print("Using np.matmul:\n", np.matmul(a_ndarray, b_ndarray))

# Using np.dot
print("Using np.dot:\n", np.dot(a_ndarray, b_ndarray))

# Using @ operator
print("Using @ operator:\n", a_ndarray @ b_ndarray)

#Problem 3: Implementation of calculation of a certain element
# Manual calculation of c[0][0]
element_00 = 0
for k in range(3):
    element_00 += a_ndarray[0][k] * b_ndarray[k][0]

print("Element [0][0]:", element_00)

#Problem 4: Creating a function that performs matrix multiplication
def matrix_multiply_scratch(A, B):
    # Gettig shape of input matrices
    rows_A, cols_A = A.shape
    rows_B, cols_B = B.shape

    # Initializing result matrix with zeros
    result = np.zeros((rows_A, cols_B), dtype=int)

    # Performing multiplication
    for i in range(rows_A):
        for j in range(cols_B):
            for k in range(cols_A):
                result[i][j] += A[i][k] * B[k][j]

    return result

# Testing the function
print("Scratch Implementation:\n", matrix_multiply_scratch(a_ndarray, b_ndarray))

#Problem 5: Judge the input whose calculation is not defined
def safe_matrix_multiply(A, B):
    if A.shape[1] != B.shape[0]:
        print("Matrix multiplication not defined: Columns of A ≠ Rows of B.")
        print(f"A shape: {A.shape}, B shape: {B.shape}")
        return None
    else:
        return matrix_multiply_scratch(A, B)

# Example with invalid matrices
d_ndarray = np.array([[-1, 2, 3], [4, -5, 6]])
e_ndarray = np.array([[-9, 8, 7], [6, -5, 4]])

# Attempting to multiply
result = safe_matrix_multiply(d_ndarray, e_ndarray)

#Problem 6: Transposition
# Transpose matrix B
b_transposed = b_ndarray.T
print("Transposed B:\n", b_transposed)

# Multiplying using np.matmul after transpose
result_transposed = np.matmul(a_ndarray, b_transposed)
print("Multiplication with Transposed B:\n", result_transposed)


Using np.matmul:
 [[  6  29 -20]
 [ 12  52  38]
 [-18 -51 -48]]
Using np.dot:
 [[  6  29 -20]
 [ 12  52  38]
 [-18 -51 -48]]
Using @ operator:
 [[  6  29 -20]
 [ 12  52  38]
 [-18 -51 -48]]
Element [0][0]: 6
Scratch Implementation:
 [[  6  29 -20]
 [ 12  52  38]
 [-18 -51 -48]]
Matrix multiplication not defined: Columns of A ≠ Rows of B.
A shape: (2, 3), B shape: (2, 3)
Transposed B:
 [[ 0  0  2]
 [ 2  2  9]
 [ 1 -8 -1]]
Multiplication with Transposed B:
 [[  7 -20  13]
 [ -4 -58 -43]
 [  7  88  95]]
